saveExact: true
blockExoticSubdeps: true
autoInstallPeers: false
minimumReleaseAge: 2880
trustPolicy: no-downgrade
strictPeerDependencies: true
strictDepBuilds: true
dedupePeers: true
shellEmulator: true
color: always

packages:
   - "packages/*"

packageExtensions:
   "eslint-plugin-jsdoc@*":
      dependencies:
         "eslint": "*"
   "vitest@*":
      dependencies:
         "vite": "*"
   "@napi-rs/wasm-runtime@*":
      dependencies:
         "@emnapi/core": "*"
         "@emnapi/runtime": "*"

trustPolicyExclude:
   - "semver@6.3.1 || 5.7.2"

minimumReleaseAgeExclude:
   - "@felixicaza/eslint-config"
   - "@felixicaza/oxfmt-config"
   - "@felixicaza/oxlint-config"
   - "@felixicaza/tsdown-config"

allowBuilds:
   esbuild: true
   simple-git-hooks: true
