blockExoticSubdeps: true
autoInstallPeers: false
minimumReleaseAge: 2880
trustPolicy: no-downgrade
strictPeerDependencies: true
strictDepBuilds: true

color: always

packages:
   - "packages/*"

packageExtensions:
   "oxlint-plugin-complexity@*":
      dependencies:
         "@oxlint/plugins": "*"

trustPolicyExclude:
   - "mrm-core@7.1.22"
   - "semver@6.3.1 || 5.7.2"

minimumReleaseAgeExclude:
   - "@felixicaza/eslint-config"
   - "@felixicaza/oxfmt-config"
   - "@felixicaza/oxlint-config"
   - "@felixicaza/tsdown-config"

allowBuilds:
   esbuild: true
   simple-git-hooks: true
