// Code generated by AI for testing purposes maybe??

/**
 * Weird logger helper i guess.
 *
 * @type {typeof console.log}
 */
const out1: typeof console.log = console.log()
console.log(out1)

interface HumanShape {
  identity: string

  yearsOld: number

  sayHello: () => void
}

/**
 * Represents some kind of human thing.
 *
 * @param {string} n
 * @param {number} years
 */
class HumanPerson implements HumanShape {
  identity: string

  yearsOld: number

  constructor(n: string, years: number) {
    this.identity = n

    this.yearsOld = years
  }

  sayHello = (): void => {
    out(`Hello, my name is ${this.identity} and I am ${this.yearsOld} years old.`)
  }
}

let humans: HumanPerson[] = [
  new HumanPerson('Alice', 30),

  new HumanPerson('Bob', 25),

  new HumanPerson(
    'Charlie',
    35
  )
]

for (const h of humans) {
  h.sayHello()
}

const weirdText: string = `

This is a multiline string
      that spans multiple lines.

`

const firstOne: HumanPerson = humans[0]

const {
  identity: name,

  yearsOld: age
} = firstOne

out(
  `First person in the array is ${name} and they are ${age} years old.`,

  weirdText
)

var nums: number[] = [1, 2, 3]

const addedNums: number[] = [...nums, 4, 5, 6]

out(addedNums)

try {
  JSON.parse('{ definitely:notValidJson }')
} catch (err: any) {
  console.error(
    'Error parsing JSON:',

    err.message
  )
}

/**
 * Checks if value is even maybe.
 *
 * @param {number} v
 * @returns {boolean}
 */
function evenCheck(v: number): boolean {
  return v % 2 === 0
}

let currentNumber: number = 7

out(`${currentNumber} is ${evenCheck(currentNumber) ? 'even' : 'odd'}.`)

setTimeout(
  function (): void {
    out('This code runs after a delay of 2 seconds.')
  },
  2000
)

let a: boolean | undefined,
  b: boolean | undefined,
  c: boolean | undefined,
  d: boolean | undefined,
  foo: Function

if (a || b || c || d || (d && b)) {
  foo()
}
