import type { OxlintConfig, DummyRuleMap } from 'oxlint'

const eslintPortedRules: DummyRuleMap = {
  'eslint-js/camelcase': ['error', { allow: ['^UNSAFE_'], ignoreGlobals: true }],
  'eslint-js/dot-notation': ['error', { allowKeywords: true }],
  'eslint-js/no-dupe-args': 'error',
  'eslint-js/no-octal': 'error',
  'eslint-js/no-octal-escape': 'error',
  'eslint-js/no-undef-init': 'error',
  'eslint-js/no-unreachable-loop': 'error',
  'eslint-js/one-var': ['error', { initialized: 'never' }],
  'eslint-js/prefer-regex-literals': ['error', { disallowRedundantWrapping: true }]
}

const eslintBuiltInRules: DummyRuleMap = {
  'accessor-pairs': ['error', { setWithoutGet: true, enforceForClassMembers: true }],
  'array-callback-return': ['error', { allowImplicit: false, checkForEach: false }],
  'constructor-super': 'error',
  curly: ['error', 'multi-line'],
  'default-case-last': 'error',
  'default-param-last': 'error',
  eqeqeq: ['error', 'smart'],
  'for-direction': 'error',
  'getter-return': 'error',
  'grouped-accessor-pairs': ['warn', 'getBeforeSet', { enforceForTSTypes: true }],
  'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
  'no-alert': 'warn',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-await-in-loop': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-console': ['warn', { allow: ['warn', 'error', 'info', 'clear'] }],
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-duplicate-imports': ['error', { allowSeparateTypeImports: true }],
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implied-eval': 'error',
  'no-import-assign': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
  'no-lone-blocks': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-new-wrappers': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-object-constructor': 'error',
  'no-param-reassign': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': ['error', { builtinGlobals: false }],
  'no-regex-spaces': 'error',
  'no-return-assign': ['error', 'except-parens'],
  'no-script-url': 'error',
  'no-self-assign': ['error', { props: true }],
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-undef': 'error',
  'no-unexpected-multiline': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': ['error', { defaultAssignment: false }],
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-expressions': ['error', { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true }],
  'no-unused-labels': 'error',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none', ignoreRestSiblings: true, vars: 'all' }],
  'no-use-before-define': ['error', { functions: false, classes: false, variables: false }],
  'no-useless-assignment': 'error',
  'no-useless-backreference': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-with': 'error',
  'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false }],
  'operator-assignment': 'warn',
  'prefer-const': ['warn', { destructuring: 'all', ignoreReadBeforeAssign: true }],
  'prefer-exponentiation-operator': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'require-await': 'error',
  'require-yield': 'error',
  'symbol-description': 'error',
  'unicode-bom': ['error', 'never'],
  'use-isnan': ['error', { enforceForIndexOf: true, enforceForSwitchCase: true }],
  'valid-typeof': ['error', { requireStringLiterals: true }],
  'vars-on-top': 'error',
  yoda: ['error', 'never']
}

/**
 * ESLint rules configuration.
 *
 * ESLint rules help enforce code quality and consistency in JavaScript/TypeScript code.
 * @see https://oxc.rs/docs/guide/usage/linter/rules.html?sort=name&dir=asc&scope=eslint
 * @see https://eslint.org/docs/latest/rules/
 */
export const eslint: OxlintConfig = {
  plugins: ['eslint'],
  // Use `import.meta.resolve()` due Oxlint does not resolve the plugin specifier
  jsPlugins: [import.meta.resolve('oxlint-plugin-eslint')],
  rules: {
    ...eslintBuiltInRules,
    ...eslintPortedRules
  }
}
